name: Assemble combined all-platform jar

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ combine-workflow ]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-linux:
    uses: ./.github/workflows/build-java-linux.yml

  build-macos:
    uses: ./.github/workflows/build-java-macos.yml
    with:
      cross_build: y

  build-win32:
    uses: ./.github/workflows/build-java-win32.yml

  assemble:
    needs: [build-linux, build-macos, build-win32]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - uses: actions/checkout@v3

    - name: Download hdf5-build-linux
      uses: actions/download-artifact@v3
      with:
        name: hdf5-build-linux
        path: hdf5-build-linux

    - name: Download hdf5-build-macos
      uses: actions/download-artifact@v3
      with:
        name: hdf5-build-macos
        path: hdf5-build-macos

    - name: Download hdf5-build-win32
      uses: actions/download-artifact@v3
      with:
        name: hdf5-build-win32
        path: hdf5-build-win32

    - name: Download Java source
      uses: actions/download-artifact@v3
      with:
        name: hdf5-java-source
        path: java-combined/src/main/java

    - name: List
      run: |
        ./releng/prepare_java_project.sh
        ls -l
        tree

    # Could build and publish here but for now just provide maven project
    # For manual build and deploy

    # - name: Set up JDK 17
    #   uses: actions/setup-java@v3
    #   with:
    #     java-version: '17'
    #     distribution: 'temurin'

    # - name: Build with Maven
    #   run: mvn --batch-mode clean verify
    #   working-directory: java-combined

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: prepared-maven-project
        path: "java-combined"

